name: glucose_plus
description: Portable lab chemical sensor with additional glucose functionality
version: 0.0.2
author: kosik.chris.j@gmail.com


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  css_colors:
  flutter_blue: ^0.3.3
  fcharts: ^0.0.9
  mailer3: ^1.1.9
  sliver_calendar: ^0.0.5
  flutter_simple_permissions: ^0.0.1
  path_provider: ^0.4.1
  cloud_firestore: ^0.7.4
  flutter_radial_menu: ^0.0.1
  flutter_slidable: ^0.4.0
  uuid: ^1.0.3
  firebase_core: ^0.2.5
  firebase_database: ^1.0.3
  numberpicker: ^0.1.5
  redux: ^3.0.0
  firebase_storage: ^1.0.2
  image_picker: ^0.4.7


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
#  fonts:
#    - family:     icomoon
#      fonts:
#        - asset:  icomoon.ttf

  assets:
    - sensor_pic.jpg
    - 2018c.tzf
    - calendarbanner.jpg
    - calendarheader.png
    - baseline-bluetooth_connected-24px.png
    - baseline-bluetooth_disabled-24px.png
    - glucoseplusicon.png
    - chemicalsicon.png
    - impedance_vs_time.png
    - impedance_vs_frequency.png
    - current_vs_voltage.png
    - current_vs_time.png
    - current_vs_frequency.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
